# Generated by Django 5.1.6 on 2026-01-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_payload', '0003_alter_securityevent_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityevent',
            name='asset_id',
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='farm_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='farm_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='geo_distance_from_baseline_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
